### ISSUE TITLE
[bug] Failing `npm run generate` command

### ISSUE THREAD

**Issue by HAUDRAUFHAUN** [roxiness/stackmix#13]
I get this error when I try to run `npm run generate` in the cloned stackmix repo:

```
[error] No files matching the pattern were found: "/Users/user/Desktop/dev/contrib/stackmix/.canvasit-temp/output-hwoajQ/**/*.{js,svelte}".
(node:37847) UnhandledPromiseRejectionWarning: Error: Command failed: npx prettier "/Users/user/Desktop/dev/contrib/stackmix/.canvasit-temp/output-hwoajQ/**/*.{js,svelte}" --write --single-quote --no-semi
[error] No files matching the pattern were found: "/Users/user/Desktop/dev/contrib/stackmix/.canvasit-temp/output-hwoajQ/**/*.{js,svelte}".

    at checkExecSyncError (child_process.js:616:11)
    at execSync (child_process.js:652:15)
    at run (/Users/user/Desktop/dev/contrib/stackmix/node_modules/canvasit/canvasit.js:131:9)
    at async _run (/Users/user/Desktop/dev/contrib/stackmix/node_modules/canvasit/canvasit.js:46:16)
    at async merge (/Users/user/Desktop/dev/contrib/stackmix/node_modules/canvasit/canvasit.js:76:20)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:37847) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:37847) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I've already tried to remove prettier from `cli.js`, but that didn't worked either. Do you have any idea what's wrong?

**Comment by jakobrosenberg** [comment]
I assume this has been fixed. If not please let us know and we'll reopen the issue.

**Comment by HAUDRAUFHAUN** [comment]
No, this is still an issue. Could that be caused by my platform (Mac OS)?

**Comment by jakobrosenberg** [comment]
Not sure to be honest. But the `npx stackmix` works?

**Comment by HAUDRAUFHAUN** [comment]
Yes

**Comment by jakobrosenberg** [comment]
No. I'm able to reproduce it too. I hope to have a fix out soon.

**Comment by jakobrosenberg** [comment]
Hopefully it's working now.

**Comment by HAUDRAUFHAUN** [comment]
Ok , nice to hear

**Comment by HAUDRAUFHAUN** [comment]
Works now, thank you @jakobrosenberg. I also tested out my changes, they seemed to work.
